// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using SavvyFix.Data;

#nullable disable

namespace SavvyFix.Migrations
{
    [DbContext(typeof(SavvyFixDbContext))]
    [Migration("20240519174638_SavvyFix")]
    partial class SavvyFix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SavvyFix.Models.Atividade", b =>
                {
                    b.Property<long>("IdAtividades")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdAtividades"));

                    b.Property<string>("ClimaAtual")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("DemandaProduto")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("HorarioAtual")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("IdCliente")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("LocalizacaoAtual")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<decimal>("PrecoVariado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("QntdProcura")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("IdAtividades");

                    b.ToTable("Atividades");
                });

            modelBuilder.Entity("SavvyFix.Models.Clientes", b =>
                {
                    b.Property<long>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdCliente"));

                    b.Property<string>("CepEndereco")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("NVARCHAR2(8)");

                    b.Property<string>("CpfClie")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("NVARCHAR2(11)");

                    b.Property<string>("NmClie")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("NumEndereco")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("RuaEndereco")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("SenhaClie")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("IdCliente");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("SavvyFix.Models.Compras", b =>
                {
                    b.Property<long>("IdCompra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdCompra"));

                    b.Property<long?>("IdProd")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("NmProd")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("QntdProd")
                        .HasColumnType("NUMBER(10)");

                    b.Property<decimal>("ValorCompra")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdCompra");

                    b.ToTable("Compra");
                });

            modelBuilder.Entity("SavvyFix.Models.Produtos", b =>
                {
                    b.Property<long>("IdProd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdProd"));

                    b.Property<string>("DescProd")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Img")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("MarcaProd")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("NmProd")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<decimal>("PrecoFixo")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdProd");

                    b.ToTable("Produtos");
                });
#pragma warning restore 612, 618
        }
    }
}
