// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using SavvyFix.Data;

#nullable disable

namespace SavvyFix.Migrations
{
    [DbContext(typeof(SavvyFixDbContext))]
    partial class SavvyFixDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SavvyFix.Models.Atividade", b =>
                {
                    b.Property<long>("IdAtividades")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdAtividades"));

                    b.Property<string>("ClimaAtual")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("DemandaProduto")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("HorarioAtual")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<long?>("IdCliente")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("LocalizacaoAtual")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<decimal>("PrecoVariado")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<int>("QntdProcura")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("IdAtividades");

                    b.HasIndex("IdCliente")
                        .IsUnique()
                        .HasFilter("\"IdCliente\" IS NOT NULL");

                    b.ToTable("Atividades");
                });

            modelBuilder.Entity("SavvyFix.Models.Clientes", b =>
                {
                    b.Property<long>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdCliente"));

                    b.Property<string>("CpfClie")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<long?>("IdEndereco")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long?>("IdEnderecoNavigationIdEndereco")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("NmClie")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("SenhaClie")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("IdCliente");

                    b.HasIndex("IdEnderecoNavigationIdEndereco");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("SavvyFix.Models.Compras", b =>
                {
                    b.Property<long?>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long?>("IdCliente"));

                    b.Property<string>("EspecificacaoProd")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<long?>("IdClienteNavigationIdCliente")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long>("IdCompra")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long?>("IdProd")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long?>("IdProdNavigationIdProd")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("NmProd")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<long?>("PrecoVariado")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long?>("PrecoVariadoNavigationIdAtividades")
                        .HasColumnType("NUMBER(19)");

                    b.Property<int>("QntdProd")
                        .HasColumnType("NUMBER(10)");

                    b.Property<decimal>("ValorCompra")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.HasKey("IdCliente");

                    b.HasIndex("IdClienteNavigationIdCliente");

                    b.HasIndex("IdProdNavigationIdProd");

                    b.HasIndex("PrecoVariadoNavigationIdAtividades");

                    b.ToTable("Compra");
                });

            modelBuilder.Entity("SavvyFix.Models.Enderecos", b =>
                {
                    b.Property<long>("IdEndereco")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdEndereco"));

                    b.Property<string>("BairroEndereco")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("CepEndereco")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("CidadeEndereco")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("EstadoEndereco")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("NumEndereco")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("RuaEndereco")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("IdEndereco");

                    b.ToTable("Endereco");
                });

            modelBuilder.Entity("SavvyFix.Models.Produtos", b =>
                {
                    b.Property<long>("IdProd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdProd"));

                    b.Property<string>("DescProd")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("MarcaProd")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("NmProd")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<decimal>("PrecoFixo")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.HasKey("IdProd");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("SavvyFix.Models.Atividade", b =>
                {
                    b.HasOne("SavvyFix.Models.Clientes", "IdClienteNavigation")
                        .WithOne("Atividade")
                        .HasForeignKey("SavvyFix.Models.Atividade", "IdCliente");

                    b.Navigation("IdClienteNavigation");
                });

            modelBuilder.Entity("SavvyFix.Models.Clientes", b =>
                {
                    b.HasOne("SavvyFix.Models.Enderecos", "IdEnderecoNavigation")
                        .WithMany("Clientes")
                        .HasForeignKey("IdEnderecoNavigationIdEndereco");

                    b.Navigation("IdEnderecoNavigation");
                });

            modelBuilder.Entity("SavvyFix.Models.Compras", b =>
                {
                    b.HasOne("SavvyFix.Models.Clientes", "IdClienteNavigation")
                        .WithMany("Compras")
                        .HasForeignKey("IdClienteNavigationIdCliente");

                    b.HasOne("SavvyFix.Models.Produtos", "IdProdNavigation")
                        .WithMany()
                        .HasForeignKey("IdProdNavigationIdProd");

                    b.HasOne("SavvyFix.Models.Atividade", "PrecoVariadoNavigation")
                        .WithMany("Compras")
                        .HasForeignKey("PrecoVariadoNavigationIdAtividades");

                    b.Navigation("IdClienteNavigation");

                    b.Navigation("IdProdNavigation");

                    b.Navigation("PrecoVariadoNavigation");
                });

            modelBuilder.Entity("SavvyFix.Models.Atividade", b =>
                {
                    b.Navigation("Compras");
                });

            modelBuilder.Entity("SavvyFix.Models.Clientes", b =>
                {
                    b.Navigation("Atividade");

                    b.Navigation("Compras");
                });

            modelBuilder.Entity("SavvyFix.Models.Enderecos", b =>
                {
                    b.Navigation("Clientes");
                });
#pragma warning restore 612, 618
        }
    }
}
